### ISSUE TITLE
Test Set Processing Discrepancy

### ISSUE THREAD

**Issue by ryangooch** [emahon/ml-rain#1]
I noticed there is a discrepancy in the averaged test set csv file and the original test file. We need to predict 717,625 records for the Kaggle competition but only have 717,620 records in avtest.csv. What happens to those other values in processing?

Additionally, the last line in every processed csv has fewer columns than any other line. We can usually just ignore this, unless it is the test data, which has 22 columns instead of 23 in that last line.

**Comment by emahon** [comment]
The original file neglected to process the final few lines because I was 
silly. Try the new master_processing.py file.

**Comment by ryangooch** [comment]
Ah, thanks!
